import { Poppins } from "next/font/google";
import { cn } from "@lib/utils";
import NavBar from "@components/NavBar";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["500"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <NavBar />
        <div className="pl-[72px] pr-[72px]">{children}</div>
      </body>
    </html>
  );
}
